#!/usr/local/bin/perl

use 5.010;
use pQuery;
use Data::Dumper;

my $binary_cookie = '/var/mobile/Containers/Data/Application/A740CCD5-428E-4E5B-A917-E553A6806368/Library/Cookies/Cookies.binarycookies';

my $url = $ARGV[0];
my $filter = $url;
$filter =~ s/(.*?)(\..*?)(\/.*)/$2/;

my $decrypt = sub {
    my $b = shift;
    my $c = `safari_cookie_bin.pl $b`;
};

#print $decrypt->($binary_cookie);

sub parse {
    my( $cookie ) = @_;
    my @c = ();

    open(my $fh,'<',\$cookie);

    while(<$fh>){
        my %c = ();
        chomp;
        ( $c{1}, $c{2}, $c3{3}, $c{4}, $c{5}, $c{6} ) =  split(' ',$_);
        push @c, {%c};
        #push @c, {%c} if $c{2} eq $filter;
    }

    return \@c;
}


my $response;
{
    my @cookie = @{parse($decrypt->($binary_cookie))};
    print Dumper(@{parse($decrypt->($binary_cookie))}) ;
    my $cookie = ' ';

    for(@cookie){
        $cookie .= $_->{6} . '=' . $_->{5} . '; ';
    }

    my $curl = qq|curl '$url' -H 'Cookie: | . $cookie . "'";; 
    $response = `$curl`;
}


pQuery($response)->find(".fbLastActiveTimestamp")->each(
    sub { print pQuery($_)->text, "\n" }
);

